trigger:
  - stable
pr:
  - stable

jobs:
  - job: "windows"
    pool:
      vmImage: "windows-2019"
    steps:
      - powershell: |
          cd builds\msvc\build
          & .\buildbase.bat ..\vs2019\libsodium.sln 16
        displayName: Compile it all
      - powershell: |
          mkdir bin\include\sodium
          Copy-Item "src\libsodium\include\sodium\*.h" -Destination "bin\include\sodium" -Recurse
          Copy-Item "src\libsodium\include\*.h" -Destination "bin\include\"
        displayName: Copy header files
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: bin
          artifactName: libsodium

  - job: "windows_old"
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - powershell: |
          cd builds\msvc\build
          & .\buildbase.bat ..\vs2017\libsodium.sln 15
        displayName: Compile it all
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: bin
          artifactName: libsodium

  - job: "windows_reallyold"
    pool:
      vmImage: "vs2015-win2012r2"
    steps:
      - powershell: |
          cd builds\msvc\build
          & .\buildbase.bat ..\vs2015\libsodium.sln 14
          & .\buildbase.bat ..\vs2013\libsodium.sln 12
          & .\buildbase.bat ..\vs2012\libsodium.sln 11
          & .\buildbase.bat ..\vs2010\libsodium.sln 10
        displayName: Compile it all
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: bin
          artifactName: libsodium
