trigger:
  - stable
pr:
  - stable

jobs:
  - job: "windows"
    pool:
      vmImage: "windows-2019"
    steps:
      - powershell: |
          cd builds\msvc\build
          & .\buildbase.bat ..\vs2019\libsodium.sln 16
        displayName: Compile it all
      - powershell: |
          mkdir bin\include\sodium
          Copy-Item "src\libsodium\include\sodium\*.h" -Destination "bin\include\sodium" -Recurse
          Copy-Item "src\libsodium\include\*.h" -Destination "bin\include\"
        displayName: Copy header files        
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: bin
          artifactName: libsodium

  - job: "windows_old"
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - powershell: |
          cd builds\msvc\build
          & .\buildbase.bat ..\vs2017\libsodium.sln 15
        displayName: Compile it all
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: bin
          artifactName: libsodium

  - job: "windows_reallyold"
    pool:
      vmImage: "vs2015-win2012r2"
    steps:
      - powershell: |
          cd builds\msvc\build
          & .\buildbase.bat ..\vs2015\libsodium.sln 14
          & .\buildbase.bat ..\vs2013\libsodium.sln 12
          & .\buildbase.bat ..\vs2012\libsodium.sln 11
          & .\buildbase.bat ..\vs2010\libsodium.sln 10
        displayName: Compile it all
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: bin
          artifactName: libsodium

  - job: "package"
    dependsOn:
      - windows
      - windows_old
      - windows_reallyold
    pool:
      vmImage: "windows-2019"
    steps:
      - powershell: |
          cd $(Build.ArtifactStagingDirectory)
          & ls
        displayName: Checking the staged files
      - powershell: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        displayName: Install chocolatey
      - powershell: |
          $Env:Path += ";C:\ProgramData\chocolatey\bin"
          choco install -y 7zip
        displayName: Install 7zip
      - powershell: |
          "C:\Program Files\7-Zip\7za.exe" a -mx=9 libsodium-msvc.zip *
        displayName: Create archive
